name: Bug Report
description: Report and issue with the Other Weather Home Assistant Integration.
labels: [bug, Needs Review]
body:

  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        Example:
          "This happened..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Explain what actually happens.
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: ha-version
    attributes:
      label: Home Assistant version
      description: You can find your Home Assistant version in **Settings > About**.
      placeholder: |
        Example: "2024.6.1"
    validations:
      required: true

  - type: input
    id: integration-version
    attributes:
      label: Integration version
      description: You can find this by going to **HACS > Other Weather.** The number beside the box is the version of the integration you are running.
      placeholder: |
        Example: "1.5.2"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Troubleshooting steps
      description: Before reporting an issue follow these troubleshooting steps to see if it solves the issue.
      options:
        - label: I have updated my Home Assistant installation to the latest version.
          required: true
        - label: I have updated the Pirate Weather Integration to the latest version.
          required: true
        - label: I have gone through the [documentation](https://github.com/TravisRoy/other-weather-ha) before opening this issue.
          required: true
        - label: I have restarted my Home Assistant installation.
          required: true
        - label: I have queried the API in my browser to confirm the issue is not with the API.
          required: true
        - label: I have not included my API key anywhere in my issue.
          required: true
        - label: I have written an informative title.
          required: true
